CONTIKI_PROJECT = multsht15
all: $(CONTIKI_PROJECT)

CONTIKI_SOURCEFILES += multsht15-sensors.c

CLEAN += $(CONTIKI_PROJECT).$(TARGET) $(CONTIKI_PROJECT).hex
CONTIKI = ../..
include $(CONTIKI)/Makefile.include
