CONTIKI_PROJECT = ledsUDPServer-example
all: $(CONTIKI_PROJECT)

APPS = ledsUDPServer

CLEAN += $(CONTIKI_PROJECT).$(TARGET) $(CONTIKI_PROJECT).hex


CONTIKI = ../..
include $(CONTIKI)/Makefile.include
