#ifndef __CC2520_CONST_ARCH_H__
#define __CC2520_CONST_ARCH_H__

#define RF_RSTN_BIT BIT4
#define RF_RSTN_Px_DIR P4DIR
#define RF_RSTN_Px_OUT P4OUT

#define RF_VREG_EN_Px_DIR P4DIR
#define RF_VREG_EN_Px_OUT P4OUT
#define RF_VREG_EN_BIT BIT3

#define RF_SPI_CS1N_BIT BIT0
#define RF_SPI_CS1N_Px_OUT P3OUT
#define RF_SPI_CS1N_Px_DIR P3DIR

#endif
