SENSORS += parallax_pir-555-28027.c

# All the directories containing code for our platform (relative path from /platform/wismote).
CONTIKI_TARGET_DIRS += $(CONTIKI)/lib/sensor/presence
# All the files of our platform.
CONTIKI_SOURCEFILES += $(SENSORS)
